accounts:
  - name: alice
    coins:
      [
        "20000token",
        "200000000stake",
        "30000token16u8h6j32s7k2d985tg7pch7t536uhtl8ucxmjh",
      ]
  - name: bob
    coins:
      [
        "10000token",
        "100000000stake",
        "29000token16u8h6j32s7k2d985tg7pch7t536uhtl8ucxmjh",
      ]
validator:
  name: alice
  staked: "100000000stake"
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"
faucet:
  name: bob
  coins: ["5token", "100000stake"]
